feat: added default language properly in core
Innoactive/TextToSpeech-Component pull request #42
Opened 2021-03-19 10:52 UTC by SimonTheSourcerer

### Description
Modified the default language handling

2021-03-19 10:57 UTC, Gusinuhe approved these changes

2021-03-19 10:57 UTC, Gusinuhe commented on Editor/ProjectSettings/TextToSpeechSectionProvider.cs
> +    public class TextToSpeechSectionProvider : IProjectSettingsSection
Missing docs all over the class

2021-03-19 11:10 UTC, Gusinuhe approved these changes

2021-03-19 14:25 UTC, Luphoxa commented
Moved here from the Core PR: 
Test Notes:
👍 Language put to EN or DE shows the corresponding hover text in EN or DE  
👍  Changing to a language that has no desktop mode txt file, the default desktop text is shown 
👎 Creating a language file for a new language (I copied and renamed the EN file and changed the text) and setting this language in the language settings does change it correctly for TTS, but the desktop mode still uses the default txt file, although a file for it exists. Maybe I forgot to add something? Need to have a look here, maybe together if you want  

Will add more results if I find something else :)

2021-03-22 13:59 UTC, tomwim approved these changes

2021-03-22 14:00 UTC, tomwim commented
Blocked until https://github.com/Innoactive/Creator/pull/266 is merged

2021-03-22 14:33 UTC, Luphoxa commented
This still happens to me
> 👎 Creating a language file for a new language (I copied and renamed the EN file and changed the text) and setting this language in the language settings does change it correctly for TTS, but the desktop mode still uses the default txt file, although a file for it exists. Maybe I forgot to add something? Need to have a look here, maybe together if you want
> 
Is this related to this branch or to https://github.com/Innoactive/Creator/pull/266 ?
Or did I name my ES file wrong? (`Creator_ES_desktop_mode`)

But I found nothing else.

2021-03-22 14:39 UTC, SimonTheSourcerer commented
Do not use the resource folders, please use the localization folder in streaming assets which would require you to create a ES_desktop_mode.json

2021-03-22 14:39 UTC, SimonTheSourcerer commented
otherwise if you try out different files setup please provide a picture of the setup otherwise i can only guess.

2021-03-22 18:23 UTC, tomwim commented
@Luphoxa does this mean you're approving this PR?

2021-03-23 08:39 UTC, Luphoxa commented
My setup is this, like you thought. But why does my EN and DE file work from here but additional languages need to go into the streaming assets?
![image](https://user-images.githubusercontent.com/15690875/112116832-f8d7c400-8bba-11eb-9fc9-df7a22e5ea4a.png)

I also created a Localization folder in StreamingAssets in the Training and it did not work
![image](https://user-images.githubusercontent.com/15690875/112117255-74397580-8bbb-11eb-9674-0d4487cfeeee.png)

Then I moved it directly to the StreamingAssets and it did not work either.
![image](https://user-images.githubusercontent.com/15690875/112117347-929f7100-8bbb-11eb-8157-5eb8dac7d3fd.png)

I think our main problem is that the usability of the localization is not that great and not explained anywhere. So I don't know if I did this right or not. And how "right" would look like.

2021-03-23 08:49 UTC, SimonTheSourcerer commented
here is the new documentation which will be published with the changes on the localization system: 
https://github.com/Innoactive/Creator/blob/develop/.Documentation/articles/innoactive-creator/localization.md

2021-03-23 09:19 UTC, SimonTheSourcerer commented
/azp run

2021-03-23 09:35 UTC, Gusinuhe approved these changes

2021-03-23 09:44 UTC, Luphoxa commented
Okay so I tried these paths:
For these, I copied the file from resources `Creator_EN_desktop_mode` and changed its name and content to es. 
I created a Trainings Folder, a Folder with the Course name, and a Localization folder for this: (this is the one suggested in the docu)
`Assets/StreamingAssets/Trainings/{Course Name}/Localization`
I created a Localization folder for these:
`Assets/StreamingAssets/Training/{Course Name}/Localization`
`Assets/StreamingAssets/Training/Localization`
`Assets/StreamingAssets/Localization`

-> I always get the default english.

In the documentation, the files are of tye .json so I tried it as json in these:
`Assets/StreamingAssets/Training/{Course Name}/Localization` -> default
`Assets/StreamingAssets/Trainings/{Course Name}/Localization` -> default

Then I additionally added an ES.json, maybe it's needed:
`Assets/StreamingAssets/Training/{Course Name}/Localization` -> default
`Assets/StreamingAssets/Trainings/{Course Name}/Localization` -> default

Defining default:
- I get the spanish Audio, but the english hover text from the default engish desktop file, not the EN file

Innoactive Language Settings:
![image](https://user-images.githubusercontent.com/15690875/112126431-bd41f780-8bc4-11eb-9560-c63f743ef50b.png)

2021-03-23 09:46 UTC, Luphoxa requested changes
I would like to be sure that additional languages apart from en and de are possible before merging.
Or if this is not part of this branch directly, but from another branch, dismiss this review here, but make sure to note down this bug.

2021-03-23 09:55 UTC, SimonTheSourcerer commented
I added this to my course/Localization:
![image](https://user-images.githubusercontent.com/8425643/112127660-f29b1500-8bc5-11eb-8404-7e4e0b53e082.png)
and I have spanish text displayed and also spanish voice. Works perfectly as it should be only thing i found, i cant

2021-03-23 10:18 UTC, Luphoxa approved these changes

2021-03-23 10:21 UTC, Luphoxa commented
The issue was that the file I copied had a `, ` at the bottom which lead to a json parser issue for my file, where I copied and adapted the text. Simon has kindly agreed to change this in the CreatorPro PR.
Now it works 👍  Thanks for your patience!

2021-03-23 10:25 UTC, merged